import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

// Generated by flutter gen-l10n — run `flutter pub get` to generate
// import 'package:bamul_cattle_insurance/core/l10n/app_localizations.dart';

/// Root application widget.
/// Theme and routing wired in Sprint 1; feature screens added in Sprint 2+.
class BamulApp extends StatelessWidget {
  const BamulApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BAMUL Cattle Insurance',
      localizationsDelegates: const [
        // AppLocalizations.delegate,       // uncomment after flutter pub get
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('kn'), // Kannada — primary
        Locale('en'), // English — fallback
      ],
      locale: const Locale('kn'),
      // router: GoRouter — wired in Sprint 2 (auth story)
      home: const Scaffold(
        body: Center(
          child: Text('BAMUL ಜಾನುವಾರು ವಿಮೆ'),
        ),
      ),
    );
  }
}
